name: fancy_fab_widget
description: An animated Floating Action Button toggle with animation.
version: 0.0.1
repository: https://github.com/edgarfroes/fancy_fab

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
